### ISSUE TITLE
Failed to download and install Ruby Gems

### ISSUE THREAD

**Issue by Facundo1337** [lockfale/msf-installer#3]
facundo@Facundo:~/msf$ ./script.sh -i

 Log file with command output and errors /tmp/msfinstall-may-14-18-223033.log
[*] Installing dependencies for Metasploit Framework
[*] Finished installing the dependencies.
[*] Installing base Ruby Gems
[*] Failed to download and install Ruby Gems for running Metasploit Framework

**Comment by digital-shokunin** [comment]
This is a garbage fire that hasn't been maintained in years. 

Try
https://github.com/digital-shokunin/kali-metasploit

Or at least the commands in the Dockerfile.
